# Generated by Django 5.2.6 on 2025-09-13 10:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField()),
                ('district_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('version_from', models.DateTimeField(default=None, null=True)),
                ('version_to', models.DateTimeField(default=None, null=True)),
                ('valid_from', models.DateTimeField(default=None, null=True)),
                ('valid_to', models.DateTimeField(default=None, null=True)),
                ('regon', models.IntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
