# Generated by Django 5.2.6 on 2025-09-13 13:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satagro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
