# Generated by Django 5.2.6 on 2025-09-13 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satagro', '0002_alter_district_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='regon',
            field=models.CharField(max_length=14, null=True, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
