# Generated by Django 5.2.6 on 2025-09-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satagro', '0004_meteowarning'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteoWarningArchive',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name_of_event', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=3)),
                ('probability', models.CharField(max_length=3)),
                ('valid_from', models.DateTimeField(default=None, null=True)),
                ('valid_to', models.DateTimeField(default=None, null=True)),
                ('published', models.DateTimeField(default=None, null=True)),
                ('content', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('office', models.CharField(blank=True, max_length=255)),
                ('districts', models.ManyToManyField(blank=True, to='satagro.district')),
            ],
        ),
    ]
