# Generated by Django 5.2.6 on 2025-09-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satagro', '0005_meteowarningarchive'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meteowarningarchive',
            index=models.Index(fields=['-valid_to'], name='satagro_met_valid_t_d1d402_idx'),
        ),
        migrations.AddIndex(
            model_name='meteowarningarchive',
            index=models.Index(fields=['-published'], name='satagro_met_publish_4d972d_idx'),
        ),
    ]
